todo_lists/urls.py
# sub urls for todo_list


from django.urls import path

from . import views

app_name = 'todo_lists'
urlpatterns = [
    # homepage
    path('', views.index, name='index'),
    # page that shows all projects
    path('projects/', views.projects, name='projects'),
    # details of a project
    path('projects/<int:project_id>/', views.project, name='project'),
    # add a new project
    path('new_project/', views.new_project, name='new_project'),

    # for creating new todo tasks by user
    path('new_todo/<int:project_id>/', views.new_todo, name='new_todo'),
    # for creating new todo tasks by user
    path('new_progress/<int:project_id>/', views.new_progress, name='new_progress'),
    # for creating new todo tasks by user
    path('new_done/<int:project_id>/', views.new_done, name='new_done'),
    
    # for editing current todo tasks
    path('edit_todo/<int:todo_id>/', views.edit_todo, name='edit_todo'),
    # for editing current in-progress tasks
    path('edit_progress/<int:progress_id>/', views.edit_progress, name='edit_progress'),
    path('progress/', views.visualisation, name='visualisation'),
    path('delete/<str:todo_id>/', views.delete_todo, name='delete_todo'),
    path('delete_project/<str:project_id>/', views.delete_project, name='delete_project'),
    path('edit_project/<str:project_id>/', views.edit_project, name='edit_project'),

    path('wiki', views.wikiMain, name='wikiMain'),
    path('wiki1', views.wiki1, name='manager_wiki1'),
    path('readwiki1', views.readwiki1, name='manager_readwiki1'),
    path('wiki2', views.wiki2, name='manager_wiki2'),
    path('readwiki2', views.readwiki2, name='manager_readwiki2'),
    path('wiki3', views.wiki3, name='manager_wiki3'),
    path('readwiki3', views.readwiki3, name='manager_readwiki3'),
    path('wiki4', views.wiki4, name='manager_wiki4'),
    path('readwiki4', views.readwiki4, name='manager_readwiki4'),
    path('wiki5', views.wiki5, name='manager_wiki5'),
    path('readwiki5', views.readwiki5, name='manager_readwiki5'),
    path('wiki6', views.wiki6, name='manager_wiki6'),
    path('readwiki6', views.readwiki6, name='manager_readwiki6'),
    path('wiki7', views.wiki7, name='manager_wiki7'),
    path('readwiki7', views.readwiki7, name='manager_readwiki7'),
    path('wiki8', views.wiki8, name='manager_wiki8'),
    path('readwiki8', views.readwiki8, name='manager_readwiki8'),



    path('resourcepage', views.resourcepage, name='resourcepage'),
    path('resource1', views.resource1, name='project_resource1'),
    path('readresource1', views.readresource1, name='project_readresource1'),
    path('resource2', views.resource2, name='project_resource2'),
    path('readresource2', views.readresource2, name='project_readresource2'),
    path('resource3', views.resource3, name='project_resource3'),
    path('readresource3', views.readresource3, name='project_readresource3'),
    path('resource4', views.resource4, name='project_resource4'),
    path('readresource4', views.readresource4, name='project_readresource4'),
    path('upload', views.upload, name='upload'),
    path('checkresource<id>', views.checkresource, name='project_checkresource'),
    path('downloadresource<id>', views.downloadresource, name='project_downloadresource'),
]

todo_lists/templates/todo_lists/assign.html
{% load static from static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="P&NP projectpage">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{%static 'project/pnpstyle.css'%}">
  <script src="{%static 'project/todo.js'%}"></script>
  <title>Project Page</title>
</head>
<body>
  <header>
    <div class="header" >
      <p><a href="http://127.0.0.1:8000"><img src="{%static 'project/pnplogo.png'%}"  alt=""></a></p>
    </div>
<!--    <div class="right">

      <div id="login" >
        <p>log-in</p>
      </div>
      <div id="register" >
        <p>Register</p>
      </div>

    </div> -->
    <div class="search">
      <div class="searchbar">
        <img src="" alt="search icon">
        <p>Search</p>
      </div>
    </div>
  </header>

  <div class="main">
    <div class="left">
      <div id="profile">
        <div id="inlineblock1">
          <img src="{%static 'project/profile.jpg'%}" alt="profile pic">
        </div>
        <div id="inlineblock2">
          <p>Job Title</p>
          <p>User Name</p>
        </div>

      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project">To do list</a></p>
      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project/progress">Progress</a></p>
      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project/assign">Assign</a></p>
      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project/resource">Resource</a></p>
      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project/wiki">Wiki</a></p>
      </div>
      <button class="logout">Log out</button>

    </div>

    <div>
        <div class="maintop">
        <p>Team Board</p>
        </div>
    </div>

todo_lists/templates/todo_lists/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="P&NP projectpage">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!--FontAwesome CDN-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"
        integrity="sha384-vSIIfh2YWi9wW0r9iZe7RJPrKwp6bG+s9QZMoITbCckVJqGCCRhc+ccxNcdpHuYu" crossorigin="anonymous">
    <!--Chartjs CDN-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
  <link rel="stylesheet" href="{% static '../static/styles/pnpstyle.css'%}">
  <script src="{% static '../static/js/todo.js'%}"></script>
  <title>base.html</title>
</head>
<body>
  <header>
    <div class="header" >
      <p><a href="{% url 'todo_lists:index' %}"><img src="{% static '../static/img/pnplogo.png'%}"  alt="pnplogo"></a></p>
    </div>

    <div class="search">
      <div class="searchbar">
        <img src="{% static '../static/img/search.png' %}" alt="search icon">
    </div>    
    </div>
  </header>
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-side-bar-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
  <!-- <div class="main"> -->
    <div class="left">
      <div id="profile">
        <div id="inlineblock1">
          <img src="{%static '../static/img/profile.png'%}" alt="profile pic">
        </div>
        <div id="inlineblock2">
          <p>Job Title</p>
          <p>User Name</p>
        </div>

      </div>
      <div class="lefttag">
        <p><a href="{% url 'todo_lists:projects' %}">To do list</a></p>
      </div>
      <div class="lefttag">
        <p><a href="{% url 'todo_lists:visualisation' %}">Progress</a></p>
      </div>
      <div class="lefttag">
        <p><a href="http://127.0.0.1:8000/project/assign">Assign</a></p>
      </div>
      <div class="lefttag">
        <p><a href="{% url 'todo_lists:resourcepage' %}">Resource</a></p>
      </div>
      <div class="lefttag">
        <p><a href="{% url 'todo_lists:wikiMain' %}">Wiki</a></p>
        
      </div>
      <button class="logout">Log out</button>

    </div>

    <div>
        <div class="maintop">
        <p>Team Board</p>
        </div>
    </div>
    {% block todo %} {% endblock %}
    {% block projects %} {% endblock %}
    {% block new-project %} {% endblock %}
    {% block new-todo %} {% endblock %}
    {% block edit-todo %} {% endblock %}
    {% block visualisation %} {% endblock %}
    {% block delete %} {% endblock %}
    {% block delete_project %} {% endblock %}
    {% block edit_project %} {% endblock %}
    {% block resources %} {% endblock %}
    {% block wiki %} {% endblock %}
     <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
      crossorigin="anonymous"></script>
  <!-- </div> -->
  {% block scripts %} {% endblock %}
<footer>
  <span style="color: white;">2021 PNP Tech Co.   Project Manage Soft Version 1.0.0</span>
</footer>
</body>
</html>

todo_lists/templates/todo_lists/delete.html
<!DOCTYPE html>
{% extends "todo_lists/base.html" %}
<!-- {% block title %}Delete Page{% endblock %} -->

{% block delete %}
{% load static %}
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Delete This Task:</h3>
            <hr>
            <form action="{% url 'todo_lists:delete_todo' todo.id %}" method="post">
                <div class="alert alert-danger">
                    <h4>Are you sure, you want to delete "{{ todo.name }}"?</h4>
                </div>
                {% csrf_token %}
                
                
                <input class="btn btn-danger btn-sm" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todo_lists/templates/todo_lists/delete_project.html
<!DOCTYPE html>
{% extends "todo_lists/base.html" %}
<!-- {% block title %}Delete Page{% endblock %} -->

{% block delete_project %}
{% load static %}
<div class="row my-4">
    <div class="col-md-6 offset-md-3">
        <div class="border p-3 bg-white">
            <h3>Delete This Task:</h3>
            <hr>
            <form action="{% url 'todo_lists:delete_project' project.id %}" method="post">
                <div class="alert alert-danger">
                    <h4>Are you sure, you want to delete "{{ project.name }}"?</h4>
                </div>
                {% csrf_token %}
                
                
                <input class="btn btn-danger btn-sm" type="submit" value="Confirm">
            </form>
        </div>
    </div>
</div>
{% endblock %}

todo_lists/templates/todo_lists/edit_progress.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block content %}

	<p><a href="{% url 'todo_lists:project' project.id %}">{{ project }}</a></p>
	
	<p>Edit in-progress task:</p>

	<form action="{% url 'todo_lists:edit_progress' project.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>
	
{% endblock content %}

todo_lists/templates/todo_lists/edit_project.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block edit_project %}

	<p><a href="{% url 'todo_lists:project' project.id %}">{{ project.name }}</a></p>
	
	<p>Edit a project:</p>

	<form action="{% url 'todo_lists:edit_project' project.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>
	
{% endblock %}

todo_lists/templates/todo_lists/edit_todo.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block edit-todo %}

	<p><a href="{% url 'todo_lists:project' project.id %}">{{ project }}</a></p>
	
	<p>Edit todo list:</p>

	<form action="{% url 'todo_lists:edit_todo' todo.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form>
	
{% endblock %}

todo_lists/templates/todo_lists/new_progress.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block content %}

	<p><a href="{% url 'todo_lists:project' project.id %}">{{ project }}</a></p>
	<a href="{% url 'todo_lists:edit_progress' project.id %}">Edit in-progress task</a>
	
	<p>Add a new in-progress task:</p>

	<form action="{% url 'todo_lists:new_progress' project.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add a in-progress task</button>
	</form>
	
{% endblock content %}

todo_lists/templates/todo_lists/new_project.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block new-project %}
	<p>Add a new project:</p>

	<form action="{% url 'todo_lists:new_project' %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Add project</button>
	</form>
	
{% endblock %}

todo_lists/templates/todo_lists/progress.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block visualisation %}
	<p>Add a new project:</p>
	<div class="card-body">
                

    </div>
	

{% endblock %}
{% block scripts %}
<canvas id="myChart" width="100" height="100"></canvas> 
<script>
$(document).ready(function() {
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        // labels: [{% for item in context %} {{ item }}, {% endfor %}],
        lables: [1,2,3],
        datasets: [{
            label: '# of Votes',
            // data: [{% for item in context.values %} {{ item }}, {% endfor %}],
            data: [1,2,3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
});







</script>
{% endblock %}

todo_lists/templates/todo_lists/project.html
<!doctype html>
{% extends "todo_lists/base.html" %}
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-main-function-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
<!-- add list button -->
{% block todo %}

	<div class="modal" id="todo_form">
	  <div class="header">
	    <div class="title">Add New List</div>
	    <button id= "titleclosebtn" class="btn close-modal">&times;</button>
	  </div>
	  <div class="body">
	    <input type="text" id="todo_input1" placeholder="Write a new task name" required/>
	    <input type="text" id="todo_input2" placeholder="Write the task description"/>
	    <input type="submit" value="Add" id="todo_submit" />
	  </div>
	</div>
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-to-do-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
<!-- todo list -->
{% load static %}
    <div class="mainright">
      <section class="inline">
        <div class="toplist">
          <div id="addDiv">To-do list
            <a href="{% url 'todo_lists:new_todo' project.id %}" class="add_task"><img src="{% static '../static/img/addd.png'%}"  alt="add_task_pic" width="25" height="25"></a>
          </div>       
          

        </div>

        <div class="innerbox">
          {% for todo in todos %}
          <div class="inner">
            <p>Name: {{ todo.name }}</p>
            <p>details: {{ todo.details }}</p>
            <div>
              
              <p><a href="{% url 'todo_lists:delete_todo' todo.id %}"><img src="{% static '../static/img/delete.png'%}"  alt="deletepic" width="12" height="15"></a></p>
              <p><a href="{% url 'todo_lists:edit_todo' todo.id %}"><img src="{% static '../static/img/edit.png'%}"  alt="editpic" width="12" height="15"></a></p>
              
            </div>
          </div>
          {% empty %}
            <li>No project has been added yet.</li>
          {% endfor %} 
        </div>

      </section>

 <!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-in-progress-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --> 
      <section class="inline">
        <div class="toplist">
          <div>In progress</div>
        </div>

        <div class="innerbox">
          {% for progress in progresses %}
          <div class="inner">
            <p>Name: {{ progress.name }}</p>
            <p>details: {{ progress.details }}</p>
          </div>
          {% empty %}
            <li>No task is now in progress.</li>
          {% endfor %}          
        </div>

      </section>
<!-- xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-done-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
      <section class="inline">
        <div class="toplist">
          <div>Done</div>
        </div>
        <div class="innerbox">
          {% for done in dones %}
          <div class="inner">
            <p>Name: {{ done.name }}</p>
            <p>details: {{ done.details }}</p>
          </div>
          {% empty %}
            <li>No task is has been done.</li>
          {% endfor %}
          
        </div>
      </section>
  	</div>
 <footer>
 </footer>
 <div id="overlay"></div>
 {% endblock %}



todo_lists/templates/todo_lists/projects.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block projects %}
{% load static %}
	<p>Projects</p>
	<a href="{% url 'todo_lists:new_project'%}">Add new project<img src="{% static '../static/img/addd.png'%}" alt="addpic" width="25" height="25"></a>
	{% for project in projects %}
	<section class="projectBox">
					<a href="{% url 'todo_lists:project' project.id %}">{{ project.name }}</a>
					
					<a href="{% url 'todo_lists:delete_project' project.id %}"><img src="{% static '../static/img/delete_project.png'%}" alt="deletepic" width="20" height="25"></a>
					<a href="{% url 'todo_lists:edit_project' project.id %}"><img src="{% static '../static/img/edit.png'%}" alt="editpic" width="25" height="25"></a>
					<p>Name: {{ project.name }}</p>
					<p>Due date: {{ project.due_date }}</p>
					<p>project_code: {{ project.project_code }}</p>
					<p>details: {{ project.details }}</p>
					<p>team: {{ project.team }}</p>

			{% empty %}
			 	<span>No project has been added yet.</span>
			{% endfor %}
	</section>
{% endblock %}

todo_lists/templates/todo_lists/visualisation.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block visualisation %}

	<p><a href="{% url 'todo_lists:project' project.id %}">{{ project }}</a></p>
	
	<p>Edit todo list:</p>

	<!-- <form action="{% url 'todo_lists:edit_todo' todo.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Save changes</button>
	</form> -->
	
{% endblock %}

todo_lists/templates/todo_lists/wiki.html
<!doctype html>
{% extends "todo_lists/base.html" %}

{% block wiki %}
    <div>
        <div class="maintop">
        <p>Wiki page</p>
        </div>
    </div>
    <div>
        <h2>Company projects</h2>
        <p>Myer website improvement. <a href="http://127.0.0.1:8000/manager/readwiki1">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki1">Click here to download</a>  <a href="https://www.myer.com.au/">   Reference</a></p>
        <p>JB HIFI online stock system.  <a href="http://127.0.0.1:8000/manager/readwiki2">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki2">Click here to download</a>  <a href="https://www.jbhifi.com.au/">   Reference</a></p>
        <p>David jones online payment system.  <a href="http://127.0.0.1:8000/manager/readwiki3">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki3">Click here to download</a>  <a href="https://www.davidjones.com/">   Reference</a></p>
        <p>Cotton on in-store employee managing system.  <a href="http://127.0.0.1:8000/manager/readwiki4">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki4">Click here to download</a>  <a href="https://cottonon.com/">   Reference</a></p>
        <h2>General company protocols</h2>
        <p>Workplace health and safety policy.  <a href="http://127.0.0.1:8000/manager/readwiki5">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki5">Click here to download</a>  <a href="https://resources.workable.com/workplace-health-and-safety-company-policy">   Reference</a></p>
        <p>Equal opportunity policy.  <a href="http://127.0.0.1:8000/manager/readwiki6">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki6">Click here to download</a>  <a href="https://resources.workable.com/equal-opportunity-company-policy">   Reference</a></p>
        <p>Employee Code of Conduct Policy.  <a href="http://127.0.0.1:8000/manager/readwiki7">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki7">Click here to download</a>  <a href="https://resources.workable.com/employee-code-of-conduct-company-policy">   Reference</a></p>
        <p>Leave of Absence Policy.  <a href="http://127.0.0.1:8000/manager/readwiki8">Click here to read.</a> <a href="http://127.0.0.1:8000/manager/wiki8">Click here to download</a>  <a href="https://resources.workable.com/sick-leave-company-policy">   Reference</a></p>


    </div>
  
  
{% endblock %}
    
